name: Security compliance

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: inigomarquinez/reusable-workflows/.github/workflows/openssf-scorecard.yml@7a428442cf347828e4d7aed9352bc40a070351d4
