name: Security compliance

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: inigomarquinez/reusable-workflows/.github/workflows/openssf-scorecard.yml@30ea0fae2439fa7b2cda42088227c19b5af2e504
