name: Security compliance

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: inigomarquinez/reusable-workflows/.github/workflows/openssf-scorecard.yml@c3a2d114b316d1dee9c6d90ac4685d6182156bac
